language: python
sudo: false
cache: pip
os: linux
dist: trusty
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - secure: V59XotjCl0kbDZaFbjPEyGyFUQIj+dFAhvLdzU3F9Hm/pB2qDRxqkrfyP/pjLNd6joTU//7cm20CWMZ0mjzJuxPq5NnM/WQSSDFlOrqYFS1NHC30A1VqBwiRX3SqEqKsT7QH0nqew0OO5dTkfABHyPu8JAEcq2nqbimoye7bJTO/5UyntLjjzirzeDp2SL5P359qD5D1zJ6rs7kos7PWNfufEK/J8IqZ5brF4P/0HovKRNDyxwfCkQ5QEgDwmiQ6WWI7N0tQrciEsav41PUCshNlTGZKTnLrVpB+eT80gkOD10yIfjqJs7fJFhE/P10MqU45/jcsHuu5U6xN/h53rx0u7I3ft8n16F6+sqL2r9ixKvuGfONpLBmEUKZXk1Rtv8Uj4T6uBnqdZTywvWNOgWYMGicpCT18bwNE8etihfkTG5q4HDRx9pYu9PMzHyA33gPQ9h3cERzw41lXI9cpDw7t+Ne1MUaJDWsMMpPFDv+B5LgNikSvmCak5joNScVCHL5fVwTIEU82Or6ouebnP3l7Xoh2Y37pqtYCdyqSv8DV4+ir8ebfSIpswM3ghZAQVkRXhWShnM108XQw68cAfhScpWTR3kuaA/Xapiga0/umFfgctiwCssxJwy+iW6sqqdRijGwv5vHFpVC4qMoPY8INclUeNa7vwAHGzV9F7AQ=
    - secure: "M11jfUy5SSaXIF1PvZMwvdcuU6b4b0+l8Bjt6XBoTrtHNYGJtcu/1XvFomvY3UJ2GhttibNAsYhjLbpMoHo4yMjsiWd5aFrL/hjEXT8ot7Q2CGyKhsUW9UBAZBG2jgqrXHSO5VstKuboo2nx0p7v1BatW8wW/Ic7FniC0T/dJK2RSaTV4Ex2JpGWXEFz0QG83BatJkD59x3VxLsM3MMPxpH6V+tiVPb49eq/xBT1fLTj3XrgRAXDj5R9y2Ag92axKqcsFla79VDuDXMr+LZ3SNWGwpT562lI4sJq56oaIk8vpZURd8G8lpqcUSAGXEXdAeSP4Kw1AV3bFz6giZyvYUdlrSGMIrq3OvHYtnNBWaUoYXR74Q0sDBw8/zQ5x+lm28L6d25bnpr3izQHLlTKJvEASDL16UbSklRd4Wb5KrCkN89PvPn0EvqXXXvzgnTsfYK+8jEoRBC/VvzL/Q92WuTMFEuyrBtJcVm78kGPoIkxBARoiyBdVwg6R62/ZI/xV3b86jUrHljBZ1HEcYNrJxStdLHeKzuq11B7J8bh1BTK5oHTiQZ7CuxCom7N1Rr/4q6ikeNynmg2J+2yOzP/O+JJJYm0D0RMDZsHXZl3+G0oH46v9MqIMbZuYlB8iYxTMp1IjKlYPMWM3pvzZWWA3GC2GCD9XAmtJ77ZXH1+jgw="
matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=2.7
    - python: '3.5'
      env:
        - TOXENV=check
    - python: '3.5'
      env:
        - TOXENV=docs
    - python: '3.5'
      env:
        - TOXENV=codacy
    - python: '3.5'
      env:
        - TOXENV=3.5
    - python: '3.6'
      env:
        - TOXENV=3.6
    - python: pypy2.7-5.8.0
      env:
        - TOXENV=pypy
    - python: pypy3.5-5.8.0
      env:
        - TOXENV=pypy3
    - python: '3.5'
      env:
        - TOXENV=3.5_marshmallow3
    - python: '3.6'
      env:
        - TOXENV=3.6_marshmallow3
    - python: pypy3.5-5.8.0
      env:
        - TOXENV=pypy3_marshmallow3
install:
  - pip install tox-travis
script:
  - tox
